Update Travis file using opam and Docker images

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,25 +1,52 @@
-addons:
-  apt:
-    packages:
-      - aspcud
-      - opam
-    sources:
-      - avsm
-before_cache:
-  - rm -rf ~/.opam/log/
-cache:
-  directories:
-    - $HOME/.opam
+dist: trusty
+sudo: required
+language: generic
+
+services:
+  - docker
+
 env:
-  - OCAML_VERSION=4.05.0 COQ_VERSION=8.5.3
-  - OCAML_VERSION=4.05.0 COQ_VERSION=8.6.1
-install:
-  - opam init -n --compiler=$OCAML_VERSION
-  - eval `opam config env`
-  - opam install -y coq.$COQ_VERSION smart-print yojson
-  - opam list
-language: c
+  global:
+  - PACKAGE_NAME="coq-of-ocaml"
+  matrix:
+  - COQ_IMAGE="coqorg/coq:8.7" SHOULD_SUPPORT="true"
+  - COQ_IMAGE="coqorg/coq:8.8" SHOULD_SUPPORT="true"
+  - COQ_IMAGE="coqorg/coq:8.9" SHOULD_SUPPORT="true"
+
+install: |
+  # Prepare the COQ container
+  docker pull ${COQ_IMAGE}
+  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/project -w /home/project ${COQ_IMAGE}
+  docker exec COQ /bin/bash --login -c "
+    # This bash script is double-quoted to interpolate Travis CI env vars:
+    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
+    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
+    set -ex  # -e = exit on failure; -x = trace for debug
+    opam switch 4.05.0
+    opam update
+    opam pin add ${PACKAGE_NAME}.opam . --kind=path --no-action
+    opam config list
+    opam repo list
+    opam pin list
+    opam list
+    " install
 script:
-  - cd OCaml && ./configure.sh && make && make install && cd ..
-  - make
-  - make test
+- echo -e "${ANSI_YELLOW}Building...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
+- |
+  docker exec COQ /bin/bash --login -c "
+    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
+    set -ex
+    sudo chown -R coq:coq /home/project
+    # Check if the package is compatible with the current environment
+    if [ ${SHOULD_SUPPORT} ] || opam install ${PACKAGE_NAME} --show-action; then
+      # First install the dependencies
+      sudo apt-get update
+      opam depext ${PACKAGE_NAME} -y
+      opam install ${PACKAGE_NAME} --deps-only -y
+      opam list
+      # Then install the package itself in verbose mode
+      opam install ${PACKAGE_NAME} -v
+    fi;
+    " script
+- docker stop COQ  # optional
+- echo -en 'travis_fold:end:script\\r'
